name: 테스트 워크플로

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: 저장소 체크아웃
        uses: actions/checkout@v3

      - name: Hello World 출력
        run: echo "안녕하세요! 워크플로 정상 작동 중입니다 :)"
